name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag backend:$(date +%s)
        docker tag backend:$(date +%s) https://docker.new-blog.store/backend:$(date +%s)
        docker push https://docker.new-blog.store/backend:$(date +%s)
        
